---
version: "3.5"
services:
    nexus-fe:
        image: registry.gitlab.dot.co.id/playground/boilerplates/vite-admiral:develop
        deploy:
            placement:
                constraints: [node.hostname == sandbox]
            resources:
                limits:
                    cpus: "0.5"
                    memory: 1G
            restart_policy:
                condition: on-failure
        ports:
        - 38293:8080

networks:
    default:
        name: docker-swarm-deployment-network
        external: true
