---
- name: Deploy environment to sandbox
  hosts: dot_sandbox
  remote_user: ajeng
  become: true
  become_user: project
  gather_facts: false
  vars:
    working_directory: "/var/www/project/boilerplates/vite-admiral"
    stack_name: "boilerplates-vite-admiral"
    container_version: "{{ lookup('env', 'CI_COMMIT_SHORT_SHA') }}"
    container_image: "registry.gitlab.dot.co.id/playground/boilerplates/vite-admiral:develop{{ container_version }}"

  tasks:
    - name: Update service docker image
      changed_when: false
      ansible.builtin.shell: |
        docker service update {{ stack_name }}_nexus-fe \
          --image {{ container_image }} \
          --with-registry-auth

    - name: Waiting deployment ready
      ansible.builtin.uri:
        url: https://vite-admiral-blrplt.dot.co.id
        validate_certs: false
      register: result
      until: "result.status == 200"
      retries: 60
      delay: 10

    - name: delete old image
      community.docker.docker_prune:
        containers: true
        images: true
        images_filters:
          dangling: false
      ignore_errors: True
